// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5Qi30F3CV4r70SSQYrVRaLWA6vq_XTb8',
    appId: '1:602031529194:web:c55112bfaebff9b4bb0b93',
    messagingSenderId: '602031529194',
    projectId: 'mobil1-f0ced',
    authDomain: 'mobil1-f0ced.firebaseapp.com',
    storageBucket: 'mobil1-f0ced.appspot.com',
    measurementId: 'G-G2G9SPSWN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0uoOH5sqSw0KkSMlKuYpek6s9HZqMg5g',
    appId: '1:602031529194:android:480ce2db98b8f8dcbb0b93',
    messagingSenderId: '602031529194',
    projectId: 'mobil1-f0ced',
    storageBucket: 'mobil1-f0ced.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQMsXXrxykrIvT-Mg2I3Knrp2QiTbmcd0',
    appId: '1:602031529194:ios:98589bb0d3798b9abb0b93',
    messagingSenderId: '602031529194',
    projectId: 'mobil1-f0ced',
    storageBucket: 'mobil1-f0ced.appspot.com',
    iosClientId: '602031529194-6aukhknhakl4h5en699j0ibisj9tn067.apps.googleusercontent.com',
    iosBundleId: 'com.example.teletipApp',
  );
}
